WIN_WIDTH = 1550
WIN_HEIGHT = 800
TILESIZE = 40
FPS = 50

PLAYER_LAYER = 4
ENEMY_LAYER = 3
BLOCK_LAYER = 2
GROUND_LAYER = 1

PLAYER_SPEED = 3
ENEMY_SPEED = 2

RED = (255, 0, 0)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
GREEN = (204, 255, 153)

tilemap = [
    'BBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'BAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'B..............................P........B',
    'B...........E...........................B',
    'B.......................................B',
    'B.......................................B',
    'B.......................................B',
    'B.............BBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'B.............BAAAAAAAAAAAAAAAAAAAAAAAAAB',
    'BBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAB',

]
